import {
  asCapabilityId,
  asFacilityId,
  asGraphNodeId,
  asHazardId,
  asIncidentId,
  asInfrastructureAssetId,
  asResourceId,
  type Capability,
  type DistrictReserveConstraint,
  type Facility,
  type Hazard,
  type Incident,
  type InfrastructureAsset,
  type Resource,
} from "@zero/domain";
import { gridNodeId } from "./grid.js";

export const CAPABILITY_IDS = {
  alsCare: asCapabilityId("cap-als-care"),
  blsCare: asCapabilityId("cap-bls-care"),
  fireSuppression: asCapabilityId("cap-fire-suppression"),
  usarRescue: asCapabilityId("cap-usar-rescue"),
  aerialRecon: asCapabilityId("cap-aerial-recon"),
  hazmatContainment: asCapabilityId("cap-hazmat-containment"),
} as const;

export const CAPABILITIES: readonly Capability[] = [
  { id: CAPABILITY_IDS.alsCare, name: "Advanced Life Support", description: "Paramedic-level trauma and cardiac care." },
  { id: CAPABILITY_IDS.blsCare, name: "Basic Life Support", description: "EMT-level stabilization and transport." },
  { id: CAPABILITY_IDS.fireSuppression, name: "Fire Suppression", description: "Structure fire and exposure control." },
  { id: CAPABILITY_IDS.usarRescue, name: "Urban Search & Rescue", description: "Collapsed-structure victim extraction." },
  { id: CAPABILITY_IDS.aerialRecon, name: "Aerial Reconnaissance", description: "Drone-based damage and hazard assessment." },
  { id: CAPABILITY_IDS.hazmatContainment, name: "Hazmat Containment", description: "Chemical/gas leak containment." },
];

const T0 = "2026-01-15T08:00:00.000Z";

export const INCIDENTS: readonly Incident[] = [
  {
    id: asIncidentId("incident-structure-collapse"),
    type: "STRUCTURE_COLLAPSE",
    status: "REPORTED",
    severity: "CRITICAL",
    location: { lat: 37.77, lon: -122.44 },
    nearestGraphNodeId: gridNodeId(0, 0),
    requiredCapabilityIds: [CAPABILITY_IDS.usarRescue],
    casualtyEstimate: 12,
    reportedAt: T0,
    updatedAt: T0,
    description: "Multi-story residential building collapse, occupants reported trapped.",
  },
  {
    id: asIncidentId("incident-fire"),
    type: "FIRE",
    status: "REPORTED",
    severity: "HIGH",
    location: { lat: 37.794, lon: -122.416 },
    nearestGraphNodeId: gridNodeId(4, 4),
    requiredCapabilityIds: [CAPABILITY_IDS.fireSuppression],
    casualtyEstimate: 3,
    reportedAt: T0,
    updatedAt: T0,
    description: "Structure fire spreading from a ruptured gas main.",
  },
  {
    id: asIncidentId("incident-mass-casualty"),
    type: "MEDICAL_MASS_CASUALTY",
    status: "REPORTED",
    severity: "HIGH",
    location: { lat: 37.782, lon: -122.44 },
    nearestGraphNodeId: gridNodeId(2, 0),
    requiredCapabilityIds: [CAPABILITY_IDS.alsCare],
    casualtyEstimate: 8,
    reportedAt: T0,
    updatedAt: T0,
    description: "Collapsed overpass, multiple vehicle occupants injured.",
  },
  {
    id: asIncidentId("incident-hazmat"),
    type: "HAZMAT",
    status: "REPORTED",
    severity: "MODERATE",
    location: { lat: 37.77, lon: -122.416 },
    nearestGraphNodeId: gridNodeId(0, 4),
    requiredCapabilityIds: [CAPABILITY_IDS.hazmatContainment],
    casualtyEstimate: 0,
    reportedAt: T0,
    updatedAt: T0,
    description: "Industrial solvent leak reported near a storage facility.",
  },
];

export const RESOURCES: readonly Resource[] = [
  {
    id: asResourceId("amb-als-1"),
    kind: "ALS_AMBULANCE",
    name: "Medic 1 (ALS)",
    status: "AVAILABLE",
    capabilityIds: [CAPABILITY_IDS.alsCare],
    currentGraphNodeId: gridNodeId(2, 2),
    homeFacilityId: asFacilityId("hospital-central"),
    districtId: "DISTRICT-CENTRAL",
    location: { lat: 37.782, lon: -122.428 },
  },
  {
    id: asResourceId("amb-als-2"),
    kind: "ALS_AMBULANCE",
    name: "Medic 2 (ALS)",
    status: "AVAILABLE",
    capabilityIds: [CAPABILITY_IDS.alsCare],
    currentGraphNodeId: gridNodeId(1, 3),
    homeFacilityId: asFacilityId("hospital-central"),
    districtId: "DISTRICT-NORTH",
    location: { lat: 37.776, lon: -122.422 },
  },
  {
    id: asResourceId("amb-bls-1"),
    kind: "BLS_AMBULANCE",
    name: "Medic 3 (BLS)",
    status: "AVAILABLE",
    capabilityIds: [CAPABILITY_IDS.blsCare],
    currentGraphNodeId: gridNodeId(3, 1),
    homeFacilityId: asFacilityId("hospital-east"),
    districtId: "DISTRICT-SOUTH",
    location: { lat: 37.788, lon: -122.434 },
  },
  {
    id: asResourceId("amb-bls-2"),
    kind: "BLS_AMBULANCE",
    name: "Medic 4 (BLS)",
    status: "AVAILABLE",
    capabilityIds: [CAPABILITY_IDS.blsCare],
    currentGraphNodeId: gridNodeId(2, 4),
    homeFacilityId: asFacilityId("hospital-east"),
    districtId: "DISTRICT-EAST",
    location: { lat: 37.782, lon: -122.416 },
  },
  {
    id: asResourceId("engine-1"),
    kind: "FIRE_ENGINE",
    name: "Engine 1",
    status: "AVAILABLE",
    capabilityIds: [CAPABILITY_IDS.fireSuppression, CAPABILITY_IDS.hazmatContainment],
    currentGraphNodeId: gridNodeId(0, 2),
    homeFacilityId: asFacilityId("hospital-central"),
    districtId: "DISTRICT-NORTH",
    location: { lat: 37.77, lon: -122.428 },
  },
  {
    id: asResourceId("engine-2"),
    kind: "FIRE_ENGINE",
    name: "Engine 2",
    status: "AVAILABLE",
    capabilityIds: [CAPABILITY_IDS.fireSuppression, CAPABILITY_IDS.hazmatContainment],
    currentGraphNodeId: gridNodeId(4, 2),
    homeFacilityId: asFacilityId("hospital-east"),
    districtId: "DISTRICT-SOUTH",
    location: { lat: 37.794, lon: -122.428 },
  },
  {
    id: asResourceId("usar-1"),
    kind: "USAR_TEAM",
    name: "USAR Task Force 1",
    status: "AVAILABLE",
    capabilityIds: [CAPABILITY_IDS.usarRescue],
    currentGraphNodeId: gridNodeId(2, 2),
    homeFacilityId: asFacilityId("hospital-central"),
    districtId: "DISTRICT-CENTRAL",
    location: { lat: 37.782, lon: -122.428 },
  },
  {
    id: asResourceId("drone-1"),
    kind: "RECON_DRONE",
    name: "Recon Drone 1",
    status: "AVAILABLE",
    capabilityIds: [CAPABILITY_IDS.aerialRecon],
    currentGraphNodeId: gridNodeId(2, 2),
    homeFacilityId: asFacilityId("hospital-central"),
    districtId: "DISTRICT-CENTRAL",
    location: { lat: 37.782, lon: -122.428 },
  },
];

export const FACILITIES: readonly Facility[] = [
  {
    id: asFacilityId("hospital-central"),
    kind: "HOSPITAL",
    name: "Central Regional Hospital",
    graphNodeId: gridNodeId(1, 1),
    location: { lat: 37.776, lon: -122.434 },
    capacity: 50,
    capacityUsed: 10,
  },
  {
    id: asFacilityId("hospital-east"),
    kind: "HOSPITAL",
    name: "Eastside Community Hospital",
    graphNodeId: gridNodeId(3, 4),
    location: { lat: 37.788, lon: -122.416 },
    capacity: 40,
    capacityUsed: 5,
  },
  {
    id: asFacilityId("shelter-north"),
    kind: "SHELTER",
    name: "North District Emergency Shelter",
    graphNodeId: gridNodeId(4, 0),
    location: { lat: 37.794, lon: -122.44 },
    capacity: 200,
    capacityUsed: 20,
  },
];

export const INFRASTRUCTURE_ASSETS: readonly InfrastructureAsset[] = [
  {
    id: asInfrastructureAssetId("bridge-17"),
    kind: "BRIDGE",
    name: "Bridge 17 (5th & Main)",
    status: "FAILED",
    graphNodeId: gridNodeId(2, 2),
    location: { lat: 37.782, lon: -122.428 },
  },
  {
    id: asInfrastructureAssetId("substation-1"),
    kind: "POWER_SUBSTATION",
    name: "Substation 1",
    status: "DEGRADED",
    graphNodeId: gridNodeId(3, 2),
    location: { lat: 37.788, lon: -122.428 },
  },
];

export const HAZARDS: readonly Hazard[] = [
  {
    id: asHazardId("hazard-aftershock-zone"),
    kind: "AFTERSHOCK_RISK",
    riskLevel: "SEVERE",
    centerLocation: { lat: 37.788, lon: -122.422 },
    radiusMeters: 900,
    affectedGraphNodeIds: [
      asGraphNodeId(gridNodeId(3, 3)),
      asGraphNodeId(gridNodeId(3, 4)),
      asGraphNodeId(gridNodeId(2, 3)),
      asGraphNodeId(gridNodeId(4, 3)),
    ],
    description: "Elevated aftershock risk over a partially-collapsed block; structures unstable.",
  },
];

/** District North must retain at least one ALS ambulance at all times. */
export const DISTRICT_RESERVES: readonly DistrictReserveConstraint[] = [
  { districtId: "DISTRICT-NORTH", resourceKind: "ALS_AMBULANCE", minimumAvailable: 1 },
];
